### ISSUE TITLE
[FE] 내 챌린지 현황 채환이는 닭가슴살을 좋아해 데모 챌린지에서 챌린지 인증 후 내 인증 현황 횟수 오류

### ISSUE THREAD

**Issue by chkim417** [kookmin-sw/capstone-2024-31#172]
![Screenshot_20240521-130905](https://github.com/kookmin-sw/capstone-2024-31/assets/51479663/0eaf1107-ee77-4ef8-8de3-a30138d20327)

## 어떤 버그인가요?

> 어떤 버그인지 간결하게 설명해주세요

## 어떤 상황에서 발생한 버그인가요?

> 챌린지 인증 후 메인 화면으로 돌아와서 바텀싯에서 나의 루틴업으로 간 후 진행중인 닭가슴살 데모챌린지에 들어가서 남은 챌린지 인증 수를 봤더니 44회/42회 남은 인증 수 -2회로 떴습니다.
하지만 그 밑에있는 수영 데모챌린지에서는 인증 수가 잘 업데이트 됐습니다.

## 예상 결과

> 1회/44회 남은 인증 챌린지 43회

**Comment by HyeeunShin** [comment]
알겠습니다
