### ISSUE TITLE
[ALL] 자기 자신 팔로우 가능 현상

### ISSUE THREAD

**Issue by chkim417** [kookmin-sw/capstone-2024-31#173]
## 어떤 버그인가요?

> 자기 자신을 팔로우 할 수 있는 현상

## 어떤 상황에서 발생한 버그인가요?

> 손 모양 인증 후 게시물 올리면 자신이 올린 게시물 페이지로 넘어가게 되는데, 이 때 자신의 게시물 우측 상단에 있는 팔로잉 버튼을 누르면 자신을 팔로우 하게 됩니다.

## 예상 결과

> 팔로잉 버튼 없애기

## 참고할만한 자료(선택)
![Screenshot_20240521-131601](https://github.com/kookmin-sw/capstone-2024-31/assets/51479663/6550180e-a2c9-4624-ac27-bc87027ca7a9)

**Comment by HyeeunShin** [comment]
근데 프로필 이미지는 왜 저렇지요..?
