### ISSUE TITLE
[AI] 모델-백엔드 연결

### ISSUE THREAD

**Issue by chkim417** [kookmin-sw/capstone-2024-31#6]
## 어떤 기능인가요?
ai모델 백엔드 연결

> 추가하려는 기능에 대해 간결하게 설명해주세요
fastapi로 모델과 백엔드(spring) 연결
## 작업 상세 내용

- [ ] 기존 제시된 데이터셋으로 학습
- [ ] 손모양 찍은 후 fine tuning
- [ ] FAST API로 연결 구체화

**Comment by sukjuhong** [comment]
온디바이스 방식으로 변경
